services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ritika02
      POSTGRES_PASSWORD: ritika
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
